version: "3"
services:
  db:
    image: postgres
    container_name: db
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres 
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ../backend/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres
    container_name: auth-db
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres 
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - ../auth-service/database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  auth:
    build: 
      context: ../auth-service
    container_name: auth
    ports:
      - "4000:4000"
    depends_on:
      auth-db: 
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PORT=4000
      - HASH=supersecret
  server:
    build: 
      context: ../backend
    container_name: server
    ports:
      - "3000:3000"
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/blog-posts"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PORT=3000
      - AUTH_URL=auth
      - AUTH_PORT=4000

    depends_on:
      db: 
        condition: service_healthy
      redis:
        condition: service_healthy
  # frontend:
  #   build: 
  #     context: ../blog-post-frontend
  #   container_name: frontend
  #   ports:
  #     - "3000:3000"

  migration-backend:
    build: 
      context: ../backend
      dockerfile: Dockerfile.migration
    container_name: migration-backend
    depends_on:
      db: 
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    
  migration-auth:
    build: 
      context: ../auth-service
      dockerfile: Dockerfile.migration
    container_name: migration-auth
    depends_on:
      auth-db: 
        condition: service_healthy
    environment:
      - DB_HOST=auth-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    
    